import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import { devangProfile, swastikPosts, yashProfile } from "./assets";

/**
 * Posts can be added here.
 * You can add default posts of your wish with different attributes
 * */

export const posts = [
  {
    _id: "1",
    content: "Hey, What's up. New to SocialSphere...",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "devang123",
        createdAt: formatDate(),
        firstName: "Devang",
        lastName: "Mehra",
        profile: devangProfile,
      },
    ],
    username: "swastik123",
    firstName: "Swastik",
    lastName: "Patro",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "2",
  },
  {
    _id: "2",
    content: "It's nice weather outside...",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "devang123",
        createdAt: formatDate(),
        firstName: "Devang",
        lastName: "Mehra",
        profile: devangProfile,
      },
    ],
    username: "devang123",
    firstName: "Devang",
    lastName: "Mehra",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "3",
  },
  {
    _id: "3",
    content: "Heavy leg workout today at gym 💪",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "devang123",
        createdAt: formatDate(),
        firstName: "Devang",
        lastName: "Mehra",
        profile: devangProfile,
      },
    ],
    username: "yash123",
    firstName: "Yash",
    lastName: "Rawat",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "4",
  },
  {
    _id: "4",
    content: "Starting corporate life from today. Excited, nervous and everything in between 🤞",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 10,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "devang123",
        createdAt: formatDate(),
        firstName: "Devang",
        lastName: "Mehra",
        profile: devangProfile,
      },
    ],
    username: "mathues123",
    firstName: "Mathues",
    lastName: "Ferraro",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "10",
  },
  {
    _id: "5",
    content: "Sitting at the airport on the way home, I'm reflecting on what an incredible week it's been",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 6,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "mathues123",
        createdAt: formatDate(),
        firstName: "Mathues",
        lastName: "Ferraro",
        profile: devangProfile,
      },
    ],
    username: "slav123",
    firstName: "Slav",
    lastName: "Romanav",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "9",
  },
  {
    _id: "6",
    content: "active learning & productive failure >>>>>>> copying things from the internet",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 15,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "mathues123",
        createdAt: formatDate(),
        firstName: "Mathues",
        lastName: "Ferraro",
        profile: devangProfile,
      },
    ],
    username: "albert123",
    firstName: "Albert",
    lastName: "Dera",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "8",
  },
  {
    _id: "7",
    content: "I just realized some of my biggest childhood inspirations have followed me here ✨ Don't even know how to react, this feels surreal. Just want to say thank you and I will not disappoint, new side projects coming soon :)",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 25,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "mathues123",
        createdAt: formatDate(),
        firstName: "Mathues",
        lastName: "Ferraro",
        profile: devangProfile,
      },
    ],
    username: "joseph123",
    firstName: "Joseph",
    lastName: "Gonzalez",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "7",
  },
  {
    _id: "8",
    content: "There are 4 people in my neighborhood that drive Lambos. Every single one of them is a PHP developer.",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 16,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "mathues123",
        createdAt: formatDate(),
        firstName: "Mathues",
        lastName: "Ferraro",
        profile: devangProfile,
      },
    ],
    username: "jurica123",
    firstName: "Jurica",
    lastName: "Koletic",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "6",
  },
  {
    _id: "9",
    content: "There are 4 people in my neighborhood that drive Lambos. Every single one of them is a PHP developer.",
    postMedia: swastikPosts[1],
    likes: {
      likeCount: 16,
      likedBy: [
        {
          _id: "3",
          firstName: "Devang",
          lastName: "Mehra",
          username: "devang123",
          profile: devangProfile,
        },
        {
          _id: "4",
          firstName: "Yash",
          lastName: "Rawat",
          username: "yash123",
          profile: yashProfile,
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: "1",
        comment: "Don't I look good",
        username: "mathues123",
        createdAt: formatDate(),
        firstName: "Mathues",
        lastName: "Ferraro",
        profile: devangProfile,
      },
    ],
    username: "john123",
    firstName: "John",
    lastName: "Doe",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    userId: "5",
  },
  
];
